# Simple workflow for deploying static content to GitHub Pages
name: Build site to ensure no errors.

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

# Allow one concurrent deployment
concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: yarn
      # This is only needed because we import locally to test rather than importing from a CDN
      - name: Build packages
        run: yarn run build-packages
      - name: Build
        run: yarn run build-site
